---

- name: Define apache_packages.
  set_fact:
    apache_packages: "{{ packages | list }}"
  when: apache_packages is not defined

- include_tasks: setup.yml

- include_tasks: configure.yml
  
- name: Ensure Apache has selected state and enabled on boot.
  service:
    name: apache2
    state: started
    enabled: yes
